### ISSUE TITLE
amcat.gettokens keeps loading

### ISSUE THREAD

**Issue by WRoose** [amcat/amcat-r#6]
I have uploaded text data in csv format to amCat and now I'm trying to create the lemmatized "token-matrix".

    library(amcatr)
    amcat.save.password("https://amcat.vu.nl", "*myusername*", "*mypassw*")
    conn = amcat.connect("https://amcat.vu.nl")
    text.tokens=amcat.gettokens(conn, project=768, articleset=18397, page_size=100)

Problem is that this text.tokens variable takes (literally?) forever to be constructed. Have to abort and restart R to "solve" this problem. I have tried varying the "page_size" command, but doesn't seem to be the issue. The same code on different data (the set i used on the workshop in Gent (15/04)) seemed to be working okay. 

Thanks for the help.

**Comment by WRoose** [comment]
Update:

    text.tokens=amcat.gettokens(conn, project=768, articleset=18397, module= "corenlp_lemmatize")

this command seems to be working fine. Still wondering what the problem was *without* the "module" and *with* the "page_size" subcomnd?

**Comment by vanatteveldt** [comment]
Sorry for the late response, for some reason I didn't get an email about the issue. 

You need to always specify the module. I think 'corenlp_lemmatize' was the default, but I changed that to a language-agnostic tokenizer that doesn't lemmatize, so it will always work. 

I disabled automatic preprocessing because of a big overhaul, I've manually assigned that set for processing. I'm still thinking what the best setup is for preprocessing in AmCAT (and how to balance server load and make sure a mistaken click doesn't mess up the system, as assigning a million English articles for Dutch syntactic analysis will really piss off the parser)

Anyway, it should work again now, let me know if it doesn't!
